language: node_js
node_js:
  - "stable"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

notifications:
  email:
    recipients:
      - mhjang@nextree.io

before_deploy:
  - npm install
  - npm run build

deploy:
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: build
    application: travel-club-front
    deployment_group: travel-club-front-group
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: namoosori-juniors/travelclub-front-ks
      branch: master