version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app/travis/travel-club-front/ks/
  - source: /nginx.conf

hooks:
  AfterInstall:
    - location: deploy-travelclub.sh
      timeout: 300